# Generated by Django 6.1 on 2026-09-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_delete_mahasiswa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
    ]
