# Generated by Django 6.1 on 2026-09-12 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('dev_tools', 'Dev Tools'), ('design_editing', 'Design Editing')], default='programming', max_length=30)),
                ('icon_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
