# Generated by Django 5.0 on 2026-09-26 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_experience_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'permissions': [('star_experience', 'Can star an experience')]},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('star_project', 'Can star a project')]},
        ),
        migrations.AlterField(
            model_name='experience',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
