# Generated by Django 5.0 on 2026-09-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_experience_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'permissions': [('edit_experience', 'Can edit an experience')]},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('edit_project', 'Can edit a project')]},
        ),
    ]
